# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Murat Özer
title: Computer Engineer
email: ozerr.murat@hotmail.com
phone: 0532 420 12 11

# Social links
twitter_username: ozerimsi
github_username:  ryuz4k1
hackerrank_username: ryuz4k1
instagram_username: ozerimsi
linkedin_username: murat-özer-96a265144

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  I'm Murat Özer. I graduated from Doğuş University <mark>Computer Engineering</mark>. In fact, after two years of studying at the school I gained as an industrial engineer, I switched to computer engineering. I think it's one of the <mark>best decisions</mark> I've ever made.
  I'm an <mark>open source</mark> person. I share a project that I have developed personally for commercial purposes. In many conversation groups I focus on <mark>solving</mark> their problems by <mark>communicating</mark> with people. Because I am doing a project by making use of the internet and the experiences of people by adding something of course. When this happens, I share what I receive from people by adding my superior labor to people and people in need again.
  I have experience in many areas. I have done more software-oriented jobs and I intend to continue my life as a software developer.
  I love <mark>helping</mark>  people, adding things to them and <mark>learning</mark> from them. There is nothing <mark>team</mark> cannot overcome if we can work with this thought in developing a project..
  I'm also developing myself by catching the opportunities to be given in the job and to make their lives easier by creating technologies that can be <mark>useful</mark> to people by specializing.

# Projects Section
projects_title: Projects #(Use this to override about projects section title)

# Experience Section
experience_title: Experience #(Use this to override about experience section title)

# Education Section
education_title: Education #(Use this to override about education section title)

reference_title: "Reference"

interests_title: "Interest"

book_title: "Books / Hobbies"

certificate_title: "Attendance Certificates"

# Books
books_content: |
  <li>Are You Smart Enough to Work at Google? - William Poundstone (NTV)</li>
  <li>Kali Linux - Abdulaziz Altuntaş (Kodlab) </li>
  <li>Introduction to internet programming with php - Faruk Kaynaklı (Abaküs)</li>
  <li>Projects with C++ - Doc.Dr. Yıldıray Yalman - Research Asst. Tolga Büyüktanır (Kodlab) </li>
  <li> 'The Art of Deception:' Controlling the Human Element of Securityn - Kevin D. Mitnick William L. Simon (ODTU)</li>
  <li> 'The Art of Intrusion:' The Real Stories Behind the Exploits of Hackers, Intruders and Deceivers - Kevin D. Mitnick William L. Simon (ODTU) </li>
  <li> 'Hackers & Painters:' Big Ideas from the Computer Age - Paul Graham (ODTU) </li>
  <li> Kariyer ve Varoluş-Bir Benlik Eylemi (Kavramlar, Olgular, Deneyimler) - Daniş Navaro (Elma) </li>
  <li> Kavram - Uygulama - Soru/Cevap / Yazılım Test Teknikleri - L. Koray Yitmen (Seçkin) </li>

# Certificates
certificate_content: |
  <li> 'M001:' MongoDB Basics Course Completion Confirmation <p> Link <a>href="https://university.mongodb.com/course_completion/0157ae47-f0ad-4006-bbad-0964325ec38b"</a></p></li>
  <li>Doğuş University Information Club 20-21 April 2017 Certificate of participation in <mark> Data Analytic </mark> analytic activity.</li>
  <li>IEEE (Institute of Electrical and Electronics Enginers) hosted by Istanbul Kültür University student community on 2-3-4 March 2018 at Istanbul Kültür University Ataköy Campus participated in the "IEEE Turkey Computer Society Congress - CSCON'18" event and successfully completed the training on <mark> Machine learning </mark> topic. </li>
  <li>Certificate of Attendance at the <mark>Career Days in Informatics</mark> event organized by Doğuş University Informatics Club on 5-6 March 2018.</li>
  <li>Artificial intelligence producing turkey / DeepCon'18 5-6 October 2018 BTK / Ankara - Deep Learning Turkey (Certificate of Attendance)</li>

# Footer
footer_show_references: true


# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed