# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Murat Özer
title: Computer Engineer
email: ozerr.murat@hotmail.com
phone: 0532 420 12 11

# Social links
twitter_username: ozerimsi
github_username:  ryuz4k1
hackerrank_username: ryuz4k1
instagram_username: ozerimsi
linkedin_username: murat-ozer

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Developing myself by catching the opportunities to be given in the job and to make their lives easier by creating technologies that can be useful to people by specializing. <mark>like this</mark>.

# Projects Section
projects_title: Projects #(Use this to override about projects section title)

# Experience Section
experience_title: Experience #(Use this to override about experience section title)

# Education Section
education_title: Education #(Use this to override about education section title)

# More Section
more_title: Interests #(Use this to override about more section title)
more_content: | 
  Data science, machine learning and big data.
  Computer vision,image processing and Natural language processing.
  Mobile Technologies like User Experience (UX) / User Interface (UI) Specialist.
  Databases and knowledge-bases.
  Programming tools, environments, and program analysis (testing, debugging, reuse, usability).

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed
